version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
